### ISSUE TITLE
Option to disable single data source from provider

### ISSUE THREAD

**Issue by Icebird2000** [rseichter/fangfrisch#10]
As in #8 the Problem already exist. 
As mention in malware.expert.fp ab1762c69439bdd1d6381726e832544f:37:buy.subscriotion.from.malware.expert for this you need a subscription.
Now i want to disable the signatures.
```
url_malwareexpert_fp = /dev/null
url_malwareexpert_hdb = /dev/null
url_malwareexpert_ldb = /dev/null
url_malwareexpert_ndb = /dev/null
```

will probably work but brings error in syslog

```
Feb  8 15:15:00 x fangfrisch[8220]: Invalid URL '/dev/null.sha256': No schema supplied. Perhaps you meant http:///dev/null.sha256?
Feb  8 15:15:00 x Traceback (most recent call last):
Feb  8 15:15:00 x File "/usr/lib/python3.8/site-packages/fangfrisch/refresh.py", line 106, in refresh
Feb  8 15:15:00 x digest = get_digest(ci)
Feb  8 15:15:00 x File "/usr/lib/python3.8/site-packages/fangfrisch/download.py", line 70, in get_digest
Feb  8 15:15:00 x download = _download(f'{ci.url}.{ci.check}', max_size)
Feb  8 15:15:00 x File "/usr/lib/python3.8/site-packages/fangfrisch/download.py", line 57, in _download
Feb  8 15:15:00 x response = _session.get(url, stream=True, timeout=30)
Feb  8 15:15:00 x File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
Feb  8 15:15:00 x return self.request('GET', url, **kwargs)
Feb  8 15:15:00 x File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
Feb  8 15:15:00 x prep = self.prepare_request(req)
Feb  8 15:15:00 x File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
Feb  8 15:15:00 x p.prepare(
Feb  8 15:15:00 x File "/usr/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
Feb  8 15:15:00 x self.prepare_url(url, params)
Feb  8 15:15:00 x File "/usr/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
Feb  8 15:15:00 x raise MissingSchema(error)
Feb  8 15:15:00 x requests.exceptions.MissingSchema: Invalid URL '/dev/null.sha256': No schema supplied. Perhaps you meant http:///dev/null.sha256?
```

**Comment by Icebird2000** [comment]
Also doppelstern.ndb and doppelstern.hdb is gone
3b583df09ec829197e03819fddf45f84:180:Doppelstern.hdb.Is.Dead.RIP

**Comment by rseichter** [comment]
I have provided a [developer release](https://test.pypi.org/project/fangfrisch/) which handles disabling URLs more gracefully. It allows setting `url_xyz = disabled`. In the current stable release 1.3.0, you can use an empty value `url_xyz =`, as mentioned in the docs.

If you have the option to use the developer release, please let me know if this solves the issue for you.

**Comment by rseichter** [comment]
Stable release 1.4.0 is now available [via PyPI](https://pypi.org/project/fangfrisch/).
