### ISSUE TITLE
fangfrisch traceback on timeout with clamd 

### ISSUE THREAD

**Issue by xpunkt** [rseichter/fangfrisch#12]
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/fangfrisch", line 33, in <module>
    sys.exit(load_entry_point('fangfrisch==1.4.0', 'console_scripts', 'fangfrisch')())
  File "/usr/lib/python3.9/site-packages/fangfrisch/__main__.py", line 64, in main
    ClamavRefresh(args).refresh_all()
  File "/usr/lib/python3.9/site-packages/fangfrisch/refresh.py", line 150, in refresh_all
    run_command(command, config.on_update_timeout(),
  File "/usr/lib/python3.9/site-packages/fangfrisch/util.py", line 92, in run_command
    p: CompletedProcess = run(command, capture_output=True, encoding='utf-8', shell=True, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1980, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib/python3.9/subprocess.py", line 1178, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command 'clamdscan --reload' timed out after 30 seconds

**Comment by rseichter** [comment]
If that's supposed to be a bug report, it is of very little use. Feel free to open a new issue if you are prepared to invest enough work on your end to make it worth my time to investigate.
