### ISSUE TITLE
Struggling with setting up Fangfrisch database on MX Linux

### ISSUE THREAD

**Issue by mochipancakes** [rseichter/fangfrisch#13]
I use MX Linux and am working on a hardened respin.

I installed Fangfrisch, following the instructions as written up to here [https://rseichter.github.io/fangfrisch/#dbsetup](url) in a root shell.

Running this command `sudo -u clamav -- fangfrisch --conf /etc/fangfrisch.conf initdb`
(even when I set my user profile to the clamav usergroup) only got me this error.
`sudo: fangfrisch: command not found`

So I was forced to run Fangfrisch, using the initdb and refresh commands as root.

When I tried to refresh the database, here's the output I got (minus the receipt number for Malware Patrol).
`(venv) root@mx:/var/lib/fangfrisch# fangfrisch --conf /etc/fangfrisch.conf -f refresh
WARNING: https://lists.malwarepatrol.net/cgi/getfile?product=32&receipt=[REDACTED]&list=clamav_basic content length unknown
ERROR: HTTPSConnectionPool(host='www.securiteinfo.com', port=443): Read timed out.
Traceback (most recent call last):
  File "/var/lib/fangfrisch/venv/lib/python3.7/site-packages/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/var/lib/fangfrisch/venv/lib/python3.7/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/lib/python3.7/http/client.py", line 461, in read
    n = self.readinto(b)
  File "/usr/lib/python3.7/http/client.py", line 505, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/fangfrisch/venv/lib/python3.7/site-packages/requests/models.py", line 758, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/var/lib/fangfrisch/venv/lib/python3.7/site-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/var/lib/fangfrisch/venv/lib/python3.7/site-packages/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/var/lib/fangfrisch/venv/lib/python3.7/site-packages/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.securiteinfo.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/fangfrisch/venv/lib/python3.7/site-packages/fangfrisch/refresh.py", line 122, in refresh
    payload = get_payload(ci)
  File "/var/lib/fangfrisch/venv/lib/python3.7/site-packages/fangfrisch/download.py", line 81, in get_payload
    return StatusDataPair(True, download.data.content)
  File "/var/lib/fangfrisch/venv/lib/python3.7/site-packages/requests/models.py", line 836, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/var/lib/fangfrisch/venv/lib/python3.7/site-packages/requests/models.py", line 765, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.securiteinfo.com', port=443): Read timed out.
ERROR: /bin/sh: 1: clamdscan: not found
`

Here are is the conf file I used.
[Fangfrisch.txt](https://github.com/rseichter/fangfrisch/files/7225366/Fangfrisch.txt)

**Comment by rseichter** [comment]
Your report hints at several unrelated aspects:

1. Starting Fangfrisch as root is _never_ required for TCP port numbers >= 1024. Not being able to launch Fangfrisch as non-root indicates configuration or file permission errors.

2. Assuming you followed the installation instructions to the letter, did you verify if the launcher script is available? As the documentation states under section 3.3, it should be found in `/var/lib/fangfrisch/venv/bin/fangfrisch` and execute permissions should already be active.

3. When starting Fangfrisch, you need to either specify the full path of the launcher script or include `/var/lib/fangfrisch/venv/bin` in your shell's PATH variable.

4. Your config file contains too much data to be easily readable. Do not include any settings which are part of the default config settings.

5. The following combination will not work, beause you configured an invalid URL. Either provide a valid customer_id or disable the provider section.

```
[securiteinfo]
customer_id = [Nope!]
prefix = https://www.securiteinfo.com/get/signatures/${customer_id}/
enabled = yes
```

6. The error message "clamdscan: not found" also means you need to either use a different PATH variable or provide the full path in the `on_update_exec` setting.

I hope this will get you started in the right direction.

**Comment by mochipancakes** [comment]
1. Configuration or file permission errors like what? How do I check or fix them?
2. I went through the installation process again to double check. This time, I added my user profile to the clamav group before going through the steps. I didn't last time which might explain what went wrong. There was a file called "fangfrisch" and I think its permission settings are good.
![hereItIs](https://user-images.githubusercontent.com/57260257/134770697-23796d6f-6abd-4e34-8f72-0ecacc6999dd.png)

4. I was using the reference script provided here [https://rseichter.github.io/fangfrisch/#sampleeff](url)
5. I deliberately redacted my customer_id and receipt number so nobody gets any bright ideas to use my own accounts for these services.
6. Full path? So where can I usually find clamdscan?

Last of all, you keep referring to this Shell's PATH variable. I'm sorry for not knowing what I'm sure must be so simple but how can I configure that?

Thank you.

**Comment by rseichter** [comment]
> Configuration or file permission errors like what?

The user account which launches Fangfrisch needs to be able to read all files associated with the application, e.g. the config file, the Python virtual environment files, and so forth. The account also needs to be able to write downloaded files to disk and to execute commands invoked via the `on_update_exec` config parameter. When using an SQLite database, the account must also be able to write to the DB file.

> There was a file called "fangfrisch" and I think its permission settings are good.

According to the screenshot, the file appears to be "world executable", that is executable by any user account. That is more than enough.

> I was using the reference script provided here https://rseichter.github.io/fangfrisch/#sampleeff

Appendix B of the documentation states: "The following effective configuration is the result of combining internal defaults (see [Appendix A](https://rseichter.github.io/fangfrisch/#internalconf)) with the example settings shown in [Section 5](https://rseichter.github.io/fangfrisch/#_configuration)". All you need is a very small config file as you can find in [section 5.1](https://rseichter.github.io/fangfrisch/#_default_providers).

> I deliberately redacted my customer_id and receipt number

Ah, I misunderstood you using "[Nope]" as an attempt to disable the provider section. My mistake.

> Full path? So where can I usually find clamdscan?

The ClamAV package for Gentoo Linux uses /usr/bin/clamdscan, but I don't know where your Linux distribution places the file. It might be found in /usr/local/bin, /opt/bin or someplace else entirely.

> Last of all, you keep referring to this Shell's PATH variable. I'm sorry for not knowing what I'm sure must be so simple but how can I configure that?

Try launching a command line terminal and execute `echo $PATH`. For common shells like `sh`, `bash` or `zsh` this will show you the directories your shell searches for executable files. Changing PATH can be done in various places depending on the actual shell flavour used, so you best refer to your chosen shell's manual page. Using absolute paths is an alternative to relying on PATH.
