### ISSUE TITLE
fangfrisch exception occured

### ISSUE THREAD

**Issue by solisinvictum** [rseichter/fangfrisch#20]
Hey,

just found out about Fangfrisch from the Archwiki (https://wiki.archlinux.org/title/ClamAV#Adding_more_databases/signatures_repositories).

Wanted to test it out in a clean Archlinux install inside KVM (virt-manager).

On Archlinux (up-to-date until few minutes ago, no desktop or something, install few minutes old and nothing installed  except installer installs himself) following error is showing:

```
>> fangfrisch refresh

Traceback (most recent call last):
  File "/usr/lib/python3.10/configparser.py", line 790, in get
    value = d[option]
  File "/usr/lib/python3.10/collections/__init__.py", line 986, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.10/collections/__init__.py", line 978, in __missing__
    raise KeyError(key)
KeyError: 'db_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/fangfrisch", line 33, in <module>
    sys.exit(load_entry_point('fangfrisch==1.6.0', 'console_scripts', 'fangfrisch')())
  File "/usr/lib/python3.10/site-packages/fangfrisch/__main__.py", line 65, in main
    DbMeta.assert_version_match()
  File "/usr/lib/python3.10/site-packages/fangfrisch/db.py", line 78, in assert_version_match
    DbMeta.init(False)
  File "/usr/lib/python3.10/site-packages/fangfrisch/db.py", line 63, in init
    db_url = config.db_url()
  File "/usr/lib/python3.10/site-packages/fangfrisch/config/config.py", line 84, in db_url
    return self.parser.get(configparser.DEFAULTSECT, DB_URL)
  File "/usr/lib/python3.10/configparser.py", line 793, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'db_url' in section: 'DEFAULT'
```
I tried fangfrisch manualy, because systemctl status fangfrisch.timer stucks here:

` systemd[1]: Started Download unofficial clamav virus definition files.`

Edit:

Just checked again, now i have following:
```

INFO: /var/lib/fangfrisch/signatures/blurl.ndb updated (348100 bytes)
INFO: /var/lib/fangfrisch/signatures/bofhland_cracked_URL.ndb updated (3448 bytes)
INFO: /var/lib/fangfrisch/signatures/bofhland_malware_attach.hdb updated (106247 bytes
```

So the Daemon seems to work. Only to run manualy not.

**Comment by rseichter** [comment]
The error messages above state that “db_url” was not found in the configuration file. Please check the Fangfrisch documentation for details.

**Comment by solisinvictum** [comment]
The db_url is in the configuration file.

```
cat /etc/fangfrisch/fangfrisch.conf 
[DEFAULT]
db_url = sqlite:////var/lib/fangfrisch/db.sqlite
[...]
```

And the db exist under /var/lib/fangfrisch

**Comment by rseichter** [comment]
Well, are you certain you passed this same config file as an argument when you started Fangfrisch manually? There is no default argument for this, deliberately so.

**Comment by solisinvictum** [comment]
Didnt specified a conf file because of that documentation: 
https://rseichter.github.io/fangfrisch/#usage

I thought -c is only needed, if conf file isnt in default path. 

So, tried with -c as normal user:

```
fangfrisch refresh -c /etc/fangfrisch/fangfrisch.conf 
ERROR: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 325, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 888, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 491, in checkout
    rec = pool._do_get()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 271, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 386, in __init__
    self.__connect()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 684, in __connect
    with util.safe_reraise():
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 680, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/fangfrisch/db.py", line 80, in assert_version_match
    dm: DbMeta = session.query(DbMeta).one()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2869, in one
    return self._iter().one()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2915, in _iter
    result = self.session.execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3364, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2198, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 325, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 888, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 491, in checkout
    rec = pool._do_get()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 271, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 386, in __init__
    self.__connect()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 684, in __connect
    with util.safe_reraise():
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 680, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
CRITICAL: Please try running "initdb"
```

As root, it seems to work:

```
sudo fangfrisch refresh -c /etc/fangfrisch/fangfrisch.conf 
[sudo] Passwort für user: 
INFO: /var/lib/fangfrisch/signatures/urlhaus.ndb updated (283091 bytes)
ERROR: /bin/sh: Zeile 1: /usr/local/bin/setup-clamav-sigs: Datei oder Verzeichnis nicht gefunden
```

But i thought, fangfrisch dont needed root? (https://wiki.archlinux.org/title/ClamAV#Option_#1:_Set_up_Fangfrisch)

**Comment by rseichter** [comment]
Fangfrisch has internal default config settings, but if you wish to use a specific file, the file path needs to be specified using “—conf”. There is no default path, because different Linux distributions have different ideas about what that default path would be. You can check Arch Linux’s fangfrisch.service to see how exactly the program is launched. AFAIK, “sudo -u clamav” is used as a prefix, but that’s for the Arch Linux package maintainer to know for certain. I don’t use Arch Linux on my own servers.

**Comment by solisinvictum** [comment]
Ok.

Then, is this normal? 

```
sudo fangfrisch refresh -c /etc/fangfrisch/fangfrisch.conf 
[sudo] Passwort für user: 
INFO: /var/lib/fangfrisch/signatures/urlhaus.ndb updated (283091 bytes)
ERROR: /bin/sh: Zeile 1: /usr/local/bin/setup-clamav-sigs: Datei oder Verzeichnis nicht gefunden
```

Is there a way to verify that the additional definitions are used by clamav? (like the eicar file)

**Comment by rseichter** [comment]
Like I wrote, I don't think that Arch Linux uses a user called "fangfrisch", but rather "clamav". This is what I recommend as well, because the files are downloaded for the ClamAV daemon after all. I also tested python-fangfrisch on a freshly created Arch Linux virtual machine, and Fangfrisch works fine, both when run via systemd timer/service and when run manually. Whatever problems you are having must therefore bei either specific to your machine, or to Arch Linux. That's not something I can help you with, and not a problem of Fangfrisch itself. Please ask the Arch Linux folks about this. I am closing this GitHub issue, because there is no bug for me to fix.

**Comment by solisinvictum** [comment]
I mean this Error:

`ERROR: /bin/sh: Zeile 1: /usr/local/bin/setup-clamav-sigs: Datei oder Verzeichnis nicht gefunden`

Says that file setup-clamav-sigs didnt exist. So the question was if it is intended or not.

So if you tested it on a fresh Archlinux Install too, than i could imagine you followed ArchWiki and the documentation of fangfrisch? 

I try again in a new VM and report.

**Comment by rseichter** [comment]
The file `/usr/local/bin/setup-clamav-sigs` is not part of Fangfrisch. Given the name, I expect it is part of Arch Linux's ClamAV package. BTW, your problems might have to do with having started Fangfrisch as `root` at one time, which should not be done. This could have screwed up file or directory permissions. Hence, you asking the Arch Linux community seems the most promising move to me.

**Comment by solisinvictum** [comment]
Ah you to fast :-) 

See my prior post. setup-clamav-sigs war my fault. 

About Root-thing: No, i never started fangfrisch as root. See OP. After you mentioned to use the -c flag, i tried root.

NVM, it seems to be ok. But a way to check if the new definition are actually used would be cool neverless.

**Comment by rseichter** [comment]
One can set `log_level = DEBUG` in the configuration file, or set `db_url = sqlite:////does/not/exist` to force an error during database access. Just get creative. 😉 Anyway, I am glad things look alright now. Enjoy using Fangfrisch.
