### ISSUE TITLE
python 3.11 issue

### ISSUE THREAD

**Issue by internethering** [rseichter/fangfrisch#21]
running with python 3.10 is no problem:

```
# /usr/lib/python-exec/python3.10/fangfrisch -c /etc/fangfrisch.conf refresh
# no output
```

but with 3.11 I get this error:

```
# /usr/lib/python-exec/python3.11/fangfrisch -c /etc/fangfrisch.conf refresh

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/fangfrisch", line 33, in <module>
    sys.exit(load_entry_point('fangfrisch==1.5.0', 'console_scripts', 'fangfrisch')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fangfrisch/__main__.py", line 64, in main
    ClamavRefresh(args).refresh_all()
  File "/usr/lib/python3.11/site-packages/fangfrisch/refresh.py", line 142, in refresh_all
    if self.refresh(ci):
       ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fangfrisch/refresh.py", line 112, in refresh
    elif not RefreshLog.is_outdated(ci.url, ci.interval):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fangfrisch/db.py", line 144, in is_outdated
    entry: RefreshLog = _query_url(url, RefreshLog._session())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fangfrisch/db.py", line 239, in _query_url
    return session.query(RefreshLog).filter(RefreshLog.url == url).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2752, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2855, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2114, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1981, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1108, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3245, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3269, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 455, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1270, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 157, in _do_get
    raise exc.TimeoutError(
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
```

**Comment by rseichter** [comment]
Which versions of Fangfrisch and SQLAlchemy are you using? The output of `pip list` would help.

**Comment by rseichter** [comment]
@internethering Unless you provide more information, I cannot investigate your issue. 😉

**Comment by rseichter** [comment]
I am closing this issue due to lack of feedback. If you provide the necessary information, the issue can be reopened at a later time.
